### ISSUE TITLE
Reformat the glossary.

### ISSUE THREAD

**Issue by JasonMorgan** [cncf/glossary#5]
Turns out a single document works well in google docs but it doesn't fit super well for a git repo. 

I propose we break the glossary down into a series of individual entries. I further propose we move from markdown to yaml for the entries so they're easier to stitch together into a final product. I've got a PR incoming that will demonstrate my intent.

**Comment by JasonMorgan** [comment]
@CathPag FYI

**Comment by JasonMorgan** [comment]
I set up a template for the individual entries.

```yaml
title: Definition Template
category: concept 
status: Feedback Appreciated # Valid values are: In progress, Completed, Feedback Appreciated, Not Started
definition: |
  A Quick summary of the concept, what it is.

  A few lines of the problem it's addressing.

  A few lines of how the thing solves the problem.
```

I'm going to take a look at a couple other places that have technical definitions. I think it might be handy to have a couple other properties, Like related terms, or see also.

Thanks,
Jason
